# Generated by Django 5.1.4 on 2025-01-16 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('image', models.ImageField(blank=True, upload_to='blogs', verbose_name='첨부파일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성날짜')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='수정날짜')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='블로그 유저')),
            ],
            options={
                'db_table': 'blogtbl',
            },
        ),
    ]
