# Generated by Django 5.1.4 on 2025-01-17 08:23

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_blogpost_tag'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='tag',
            field=taggit.managers.TaggableManager(help_text='여러개의 태그를 원하시면 , 로 구분가능 합니다', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
