# Generated by Django 5.1.4 on 2025-01-14 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_post_photo2'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo3',
            field=models.ImageField(blank=True, upload_to='blog/%Y/%m/%d'),
        ),
    ]
