# Generated by Django 5.1.4 on 2025-01-22 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_answer_voter'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='viewcnt',
            field=models.IntegerField(default=0, verbose_name='조회수'),
        ),
    ]
