# Generated by Django 5.1.4 on 2025-01-22 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_question_viewcnt'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=30, verbose_name='ip주소')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.question', verbose_name='질문')),
            ],
        ),
    ]
